
services:
  db:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: taskmanager
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: task-manager-backend
    restart: always
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://admin:admin@postgres:5432/taskmanager
    ports:
      - "5000:5000"
    volumes:
      - ./appbackend:/app
    command: npm run dev
  
  frontend:
    build:
      context: ./frontend
    container_name: task-manager-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - app/node_modules
    stdin_open: true
    tty: true
    command: npm start
  
volumes:
  pgdata:
